# AI³ Assistant Configurations
# Defines the 15 specialized assistants with their cognitive profiles and capabilities

general:
  role: "General Purpose Assistant"
  capabilities: ["general", "help", "information", "conversation"]
  tools: ["rag", "web_scraping"]
  cognitive_settings:
    max_cognitive_load: 7
    complexity_weights:
      word_count: 1.0
      questions: 1.5
      technical_terms: 1.8
      complex_requests: 2.0

offensive_ops:
  role: "Offensive Operations Specialist"
  capabilities: ["security", "penetration_testing", "vulnerability_assessment", "red_team"]
  tools: ["rag", "web_scraping", "file_access"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.2
      questions: 2.0
      technical_terms: 3.0
      complex_requests: 3.5

influencer:
  role: "Social Media Influencer Assistant"
  capabilities: ["social_media", "content_creation", "marketing", "engagement"]
  tools: ["rag", "web_scraping", "multimedia"]
  cognitive_settings:
    max_cognitive_load: 6
    complexity_weights:
      word_count: 0.8
      questions: 1.2
      technical_terms: 1.5
      complex_requests: 2.0

lawyer:
  role: "Legal Assistant and Advisor"
  capabilities: ["legal", "law", "contracts", "compliance", "research"]
  tools: ["rag", "web_scraping", "file_access"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.5
      questions: 2.5
      technical_terms: 2.8
      complex_requests: 3.0

trader:
  role: "Financial Trading Assistant"
  capabilities: ["trading", "finance", "market_analysis", "investment", "cryptocurrency"]
  tools: ["rag", "web_scraping", "real_time_data"]
  cognitive_settings:
    max_cognitive_load: 7
    complexity_weights:
      word_count: 1.0
      questions: 2.0
      technical_terms: 2.5
      complex_requests: 2.8

architect:
  role: "Software Architecture Assistant"
  capabilities: ["architecture", "design", "systems", "software_engineering", "patterns"]
  tools: ["rag", "web_scraping", "file_access", "code_analysis"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.3
      questions: 2.2
      technical_terms: 3.2
      complex_requests: 3.5

hacker:
  role: "Ethical Hacking Assistant"
  capabilities: ["ethical_hacking", "cybersecurity", "network_security", "malware_analysis"]
  tools: ["rag", "web_scraping", "file_access", "network_tools"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.2
      questions: 2.0
      technical_terms: 3.0
      complex_requests: 3.5

chatbot_snapchat:
  role: "Snapchat Chatbot Assistant"
  capabilities: ["snapchat", "social_messaging", "multimedia", "filters"]
  tools: ["rag", "multimedia", "image_processing"]
  cognitive_settings:
    max_cognitive_load: 5
    complexity_weights:
      word_count: 0.6
      questions: 1.0
      technical_terms: 1.2
      complex_requests: 1.5

chatbot_onlyfans:
  role: "OnlyFans Content Assistant"
  capabilities: ["content_creation", "subscription_management", "audience_engagement"]
  tools: ["rag", "multimedia", "content_planning"]
  cognitive_settings:
    max_cognitive_load: 6
    complexity_weights:
      word_count: 0.8
      questions: 1.2
      technical_terms: 1.5
      complex_requests: 2.0

personal:
  role: "Personal Assistant"
  capabilities: ["personal_tasks", "scheduling", "reminders", "organization"]
  tools: ["rag", "calendar", "notifications"]
  cognitive_settings:
    max_cognitive_load: 6
    complexity_weights:
      word_count: 0.9
      questions: 1.3
      technical_terms: 1.5
      complex_requests: 2.0

music:
  role: "Music Production Assistant"
  capabilities: ["music", "audio", "production", "composition", "mixing"]
  tools: ["rag", "audio_tools", "multimedia"]
  cognitive_settings:
    max_cognitive_load: 7
    complexity_weights:
      word_count: 1.0
      questions: 1.8
      technical_terms: 2.2
      complex_requests: 2.5

material_repurposing:
  role: "Material Science and Repurposing Specialist"
  capabilities: ["materials", "recycling", "sustainability", "chemistry", "engineering"]
  tools: ["rag", "web_scraping", "scientific_databases"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.4
      questions: 2.5
      technical_terms: 3.0
      complex_requests: 3.2

seo:
  role: "SEO and Digital Marketing Assistant"
  capabilities: ["seo", "digital_marketing", "analytics", "content_optimization"]
  tools: ["rag", "web_scraping", "analytics_tools"]
  cognitive_settings:
    max_cognitive_load: 7
    complexity_weights:
      word_count: 1.0
      questions: 1.8
      technical_terms: 2.0
      complex_requests: 2.5

medical:
  role: "Medical Information Assistant"
  capabilities: ["medical", "health", "healthcare", "research", "clinical"]
  tools: ["rag", "medical_databases", "web_scraping"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.5
      questions: 2.8
      technical_terms: 3.2
      complex_requests: 3.5

propulsion_engineer:
  role: "Propulsion Engineering Specialist"
  capabilities: ["propulsion", "aerospace", "engineering", "rockets", "engines"]
  tools: ["rag", "simulation_tools", "engineering_databases"]
  cognitive_settings:
    max_cognitive_load: 8
    complexity_weights:
      word_count: 1.4
      questions: 2.5
      technical_terms: 3.5
      complex_requests: 3.8

linux_openbsd_driver_translator:
  role: "Linux/OpenBSD Driver Translation Specialist"
  capabilities: ["linux", "openbsd", "drivers", "kernel", "system_programming"]
  tools: ["rag", "source_code_analysis", "documentation_tools"]
  cognitive_settings:
    max_cognitive_load: 9
    complexity_weights:
      word_count: 1.5
      questions: 2.8
      technical_terms: 4.0
      complex_requests: 4.2