# AI³ Configuration File
# Enterprise-grade AI assistant platform configuration

# System Configuration
system:
  name: "AI³"
  version: "12.3.0"
  environment: "production"
  
  # Logging Configuration
  logging:
    level: "INFO"
    file: "ai3.log"
    rotation: "daily"
    max_size: "10MB"
    max_files: 30

# LLM Configuration
llm:
  primary: "xai"
  fallback_enabled: true
  timeout: 30
  max_retries: 3
  
  providers:
    openai:
      name: "OpenAI GPT"
      api_key: "${OPENAI_API_KEY}"
      model: "gpt-4"
      max_tokens: 2048
    
    anthropic:
      name: "Anthropic Claude"
      api_key: "${ANTHROPIC_API_KEY}"
      model: "claude-3-sonnet-20240229"
      max_tokens: 2048
    
    xai:
      name: "xAI Grok"
      api_key: "${XAI_API_KEY}"
      model: "grok-beta"
      max_tokens: 2048
    
    ollama:
      name: "Ollama Local"
      base_url: "http://localhost:11434"
      model: "llama2"
      timeout: 60

# Cognitive Architecture Configuration
cognitive:
  max_working_memory: 7
  cognitive_load_threshold: 6.5
  circuit_breaker_threshold: 0.85
  flow_state_enabled: true
  
  # Memory management
  memory:
    short_term_capacity: 10
    long_term_enabled: true
    eviction_strategy: "cognitive_load_aware"

# Session Management
session:
  max_sessions: 20
  session_timeout: 3600 # 1 hour
  eviction_strategy: "cognitive_load_aware"
  context_transfer_enabled: true

# RAG (Retrieval Augmented Generation) Configuration
rag:
  enabled: true
  vector_db_path: "data/vector_store.db"
  chunk_size: 1000
  chunk_overlap: 200
  similarity_threshold: 0.7
  max_results: 10
  
  # Vector database configuration
  vector_db:
    type: "sqlite" # or "weaviate" when available
    weaviate:
      base_uri: "${WEAVIATE_BASE_URI}"
      api_key: "${WEAVIATE_API_KEY}"
      timeout: 30

# Web Scraping Configuration
scraper:
  enabled: true
  screenshot_dir: "data/screenshots"
  max_depth: 2
  timeout: 30
  user_agent: "AI3-Bot/1.0"
  
  # Browser configuration
  browser:
    headless: true
    window_size: [1920, 1080]
    disable_gpu: true
    no_sandbox: true

# Assistant Configuration
assistants:
  default_assistant: "casual"
  enable_swarm_mode: true
  max_swarm_agents: 10
  
  # Assistant-specific configurations
  casual:
    enabled: true
    timeout: 30
    
  legal:
    enabled: true
    timeout: 60
    specializations: ["contract_law", "intellectual_property", "litigation"]
    
  architect:
    enabled: true
    timeout: 45
    specializations: ["structural_design", "urban_planning", "sustainability"]
    
  music:
    enabled: true
    timeout: 120
    swarm_agents: 10
    genres: ["electronic", "classical", "hip_hop", "rock", "jazz", "ambient", "pop", "reggae", "experimental", "cinematic"]
    
  manufacturing:
    enabled: true
    timeout: 60
    specializations: ["3d_printing", "aerospace", "automotive", "materials"]
    
  security:
    enabled: true
    timeout: 90
    tools: ["nmap", "metasploit", "burp_suite"]
    
  seo:
    enabled: true
    timeout: 45
    tools: ["keyword_analysis", "competitor_analysis", "content_optimization"]
    
  social_media:
    enabled: true
    timeout: 60
    platforms: ["discord", "snapchat", "tinder", "instagram", "twitter"]

# Social Media Automation Configuration
social_media:
  discord:
    enabled: false # Set to true when Discord token is available
    token: "${DISCORD_BOT_TOKEN}"
    command_prefix: "!"
    
  automation:
    enabled: false # Enable with caution and appropriate permissions
    rate_limit_delay: 2 # seconds between actions
    max_daily_interactions: 100
    
    # CSS detection using AI
    css_detection:
      enabled: true
      screenshot_analysis: true
      openai_vision_model: "gpt-4-vision-preview"

# Security Configuration
security:
  api_key_encryption: true
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_limit: 10
  
  # OpenBSD security features (when available)
  openbsd:
    pledge_enabled: false # Set to true on OpenBSD systems
    unveil_enabled: false # Set to true on OpenBSD systems
    allowed_paths:
      - "/usr/local/bin"
      - "/tmp"
      - "."

# Data Storage Configuration
storage:
  data_directory: "data"
  backup_enabled: true
  backup_interval: 86400 # 24 hours
  max_backups: 7
  
  # Database configuration
  database:
    type: "sqlite"
    path: "data/ai3.db"
    pool_size: 5
    timeout: 30

# Performance Configuration
performance:
  parallel_processing: true
  max_concurrent_requests: 5
  cache_enabled: true
  cache_ttl: 3600 # 1 hour
  
  # Resource limits
  limits:
    max_memory_mb: 1024
    max_cpu_percent: 80
    max_file_descriptors: 1000

# Development Configuration
development:
  debug_mode: false
  hot_reload: false
  profiling_enabled: false
  
  # Testing configuration
  testing:
    mock_llm_responses: false
    mock_web_scraping: false
    test_data_path: "test/fixtures"

# Integration Configuration
integrations:
  langchain:
    enabled: true
    verbose: false
    
  weaviate:
    enabled: false # Enable when Weaviate is available
    auto_create_schema: true
    
  ferrum:
    enabled: true
    browser_path: null # Use system default
    
  # External APIs
  external_apis:
    rate_limiting: true
    timeout: 30
    retry_attempts: 3

# Monitoring and Analytics
monitoring:
  enabled: true
  metrics_collection: true
  performance_tracking: true
  
  # Health checks
  health_checks:
    interval: 300 # 5 minutes
    endpoints:
      - "cognitive_orchestrator"
      - "llm_manager"
      - "rag_engine"
      - "session_manager"

# Internationalization
i18n:
  default_locale: "en"
  available_locales: ["en", "es", "fr", "de", "ja"]
  fallback_locale: "en"

# Feature Flags
features:
  swarm_agents: true
  collaborative_mode: true
  advanced_reasoning: true
  cognitive_monitoring: true
  auto_context_switching: true
  dynamic_css_detection: true
  multi_llm_routing: true
  rag_enhancement: true